### ISSUE TITLE
Create check like isGitLabAvailable

### ISSUE THREAD

**Issue by mikkeschiren** [loblaw-sre/backstage-plugin-gitlab#11]
To get a less cluttered interface in Backstage, if think it should be great to have somethin like [isGitLabAvailable](url) - so if there is no Gitlab annotation, Gitlab tab is not showed in the interface (there are similar functions in Lighthouse - `isLighthouseAvailable` and in Github Actions - `isGithubActionsAvailable`).

Example:
```
    </EntityLayout.Route>
        <EntityLayout.Route if={isLighthouseAvailable} path="/lighthouse" title="Lighthouse">
      <EntityLighthouseContent />
    </EntityLayout.Route>
    <EntityLayout.Route if={isGitLabAvailable} path="/gitlab" title="Gitlab">
      <EntityGitlabContent />
    </EntityLayout.Route>
 ```

**Comment by satrox28** [comment]
@mikkeschiren Sure, we will work on it.

**Comment by satrox28** [comment]
Changes are pushed https://github.com/loblaw-sre/backstage-plugin-gitlab/pull/13
