### ISSUE TITLE
Adding Issue Table

### ISSUE THREAD

**Issue by Abhay-soni-developer** [loblaw-sre/backstage-plugin-gitlab#136]
adding an issue table to easily monitor and track issues
<img width="1145" alt="issue table ui" src="https://user-images.githubusercontent.com/23618736/178586470-d2eec392-a171-47c2-80d3-3aadab8ce997.png">
.

**Comment by Abhay-soni-developer** [comment]
#135 branch containing the new issue table.
open for recommendations and discussion.

**Comment by satrox28** [comment]
Thanks for your contribution, will check and get back to you. @Abhay-soni-developer

**Comment by satrox28** [comment]
Thanks for your contribution, its released on v0.1.24
