### ISSUE TITLE
Getting code error after adding plugin and running service

### ISSUE THREAD

**Issue by sjamidar** [loblaw-sre/backstage-plugin-gitlab#18]
![image](https://user-images.githubusercontent.com/85929731/135223052-5977943f-0828-43cd-a8cd-ada1ff7ea067.png)
After Service creation , I am getting above error on click of Gitlab Tab.
Not sure what's the issue

**Comment by satrox28** [comment]
Hi @sjamidar 

Do you have integration enabled for Gitlab on app-config.yaml and added the proxy configuration as in README?.

3) Add integration: In app-config.yaml add the integration for gitlab:
integrations:
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}

4) Add proxy config:
  '/gitlabci':
    target: '${GITLAB_URL}/api/v4'
    allowedMethods: ['GET']
    headers:
      PRIVATE-TOKEN: '${GITLAB_TOKEN}'

**Comment by sjamidar** [comment]
Yes
I added all these configuration as per mentioned in Readme file for
backstage plugin gitlab

**Comment by satrox28** [comment]
Hi @sjamidar 

We released plugin version 0.1.14 today, please check.

**Comment by sjamidar** [comment]
Thanks @satrox28 , It worked. Closing the issue.
