### ISSUE TITLE
GitLab Pipeline is not visible in Catalog section of Backstage component

### ISSUE THREAD

**Issue by uday-2112** [loblaw-sre/backstage-plugin-gitlab#187]
Hi Team,
I am not able to view the Gitlab pipeline in the catalog section of Backstage Component after installing Gitlab Plugin.
we have tried using both the ways i.e., via  gitlab.com/project-id, gitlab.com/project-slug.
As per my information if we use project-id, then we might need to create a custom action but even if we are using project-slug then we must be able to view Gitlab pipeline information.
I am also adding my catalog-info.yaml below:

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: This is app service template #${{values.description | dump}}
  {%- endif %}
  annotations:
   # gitlab.com/project-id: 'project-id'
    gitlab.com/project-slug: 'group-name/${{values.repo_name}}' 
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}

@Balasundaram @saipurnima @satrox28 @NishkarshRaj Could you please help me in resolving the issue.

**Comment by satrox28** [comment]
Hi @uday-2112 

Hope, when you registered the component it has the actual values. Is it a self-hosted gitlab instance?. Can you send me any screenshot what do you see on the browser when accessing the gitlab plugin tab.

**Comment by uday-2112** [comment]
@satrox28 Thanks for your quick reply and your time.
The issue is resolved now and it was due to misconfiguration from our side.

proxy:
  '/gitlabci':

**Comment by satrox28** [comment]
Great to hear it, closing the issue. Feel free to re-open if you notice any issue.
