### ISSUE TITLE
Make web url link either a button or hyperlink for pipeline ID

### ISSUE THREAD

**Issue by maxhuebler** [loblaw-sre/backstage-plugin-gitlab#3]
I had a suggestion that it would be nice to either have a button/copy icon or hyperlink to open a pipeline ID? 

Thanks

**Comment by satrox28** [comment]
Sure, we will make a patch for it.

**Comment by satrox28** [comment]
0.1.9 package version to address this feature request @maxhuebler 

Closing the issue, feel free to re-open if its doesn't meet the requirement.
