### ISSUE TITLE
TypeError: mergeRequests.data is undefined

### ISSUE THREAD

**Issue by JarrodJ83** [loblaw-sre/backstage-plugin-gitlab#62]
I've followed the steps outlined for adding this plugin but when I go to the "Gitlab" tab I'm presented with this error. Below is the stack trace. Not sure if this is a bug or if I've done something wrong.

## Configuration:

- Gitlab integration configured
- Proxy for /gitlabci is configured
- EntityPage updated to add the Gitlab component tab
- catalog-info.yaml updated to have the `gitlab.com/project-id:` set correctly (also tried slug)

## Expected Behavior:
When navigating to the Gitlab tab on the component the below exception is rendered in the UI

## Actual Behavior:
Exception thrown

Stack Trace

DenseTable$1@webpack-internal:///../../node_modules/@loblaw/backstage-plugin-gitlab/dist/index.esm.js:1808:16
renderWithHooks@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:14804:27
mountIndeterminateComponent@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:17483:13
beginWork@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:18597:16
callCallback@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:189:14
invokeGuardedCallbackDev@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:238:16
invokeGuardedCallback@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:293:31
beginWork$1@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:23204:28
performUnitOfWork@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22155:12
workLoopSync@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22131:22
performSyncWorkOnRoot@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:21757:9
flushSyncCallbackQueueImpl/<@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:11090:24
unstable_runWithPriority@webpack-internal:///../../node_modules/scheduler/cjs/scheduler.development.js:653:12
runWithPriority$1@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:11040:10
flushSyncCallbackQueueImpl@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:11085:24
flushSyncCallbackQueue@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:11073:3
scheduleUpdateOnFiber@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:21200:9
dispatchAction@webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:15661:17
useAsyncFn/callback</<@webpack-internal:///../../node_modules/react-use/esm/useAsyncFn.js:27:61

## Environment

OS:   Windows_NT 10.0.19043 - win32/x64
node: v14.17.1
yarn: 1.22.5
cli:  0.10.4 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.3
  @backstage/backend-common                                0.10.1
  @backstage/backend-tasks                                 0.1.1
  @backstage/catalog-client                                0.5.3
  @backstage/catalog-model                                 0.9.8
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.10.4
  @backstage/config-loader                                 0.9.1
  @backstage/config                                        0.1.11
  @backstage/core-app-api                                  0.3.0
  @backstage/core-components                               0.7.6, 0.8.2
  @backstage/core-plugin-api                               0.1.13, 0.2.2, 0.4.0
  @backstage/errors                                        0.1.5
  @backstage/integration-react                             0.1.17
  @backstage/integration                                   0.7.0
  @backstage/plugin-api-docs                               0.6.20
  @backstage/plugin-app-backend                            0.3.21
  @backstage/plugin-auth-backend                           0.6.0
  @backstage/plugin-catalog-backend                        0.19.4
  @backstage/plugin-catalog-import                         0.7.7
  @backstage/plugin-catalog-react                          0.6.9
  @backstage/plugin-catalog                                0.7.6
  @backstage/plugin-github-actions                         0.4.29
  @backstage/plugin-org                                    0.3.32
  @backstage/plugin-permission-common                      0.3.0
  @backstage/plugin-permission-react                       0.2.0
  @backstage/plugin-proxy-backend                          0.2.15
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.7
  @backstage/plugin-scaffolder-backend                     0.15.19
  @backstage/plugin-scaffolder-common                      0.1.2
  @backstage/plugin-scaffolder                             0.11.16
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.3.0
  @backstage/plugin-search                                 0.5.3
  @backstage/plugin-tech-radar                             0.5.0
  @backstage/plugin-techdocs-backend                       0.12.2
  @backstage/plugin-techdocs                               0.12.12
  @backstage/plugin-user-settings                          0.3.14
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.11.2
  @backstage/test-utils                                    0.2.1
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1

**Comment by satrox28** [comment]
Hi @JarrodJ83 

Thanks for using the Gitlab Plugin. Can you provide more information, if the Gitlab project have a merge request?.

**Comment by JarrodJ83** [comment]
It was failing for multiple repos. One for sure had MRs. The other does now but hard to say if it did when I originally reported this but there is a good chance it did.

**Comment by satrox28** [comment]
Hi @JarrodJ83 are you using gitlab.com to host repos or self hosted.

Can you check the target under /gitlabci for proxy.

**Comment by JarrodJ83** [comment]
Hi @satrox28 thank you I was missing the proxy configuration. Sorry for the confusion and thanks for pointing me in the right direction.
