### ISSUE TITLE
Can you add some more info about contributers

### ISSUE THREAD

**Issue by arifrahman4u** [loblaw-sre/backstage-plugin-gitlab#68]
Hi, that's grate work...!! congratulations...

can you add more information about contributor, like how many commit he/she has done.
more information like GitHub Insight Plugin...

Thanks again for developing this...

**Comment by satrox28** [comment]
Hi @arifrahman4u 

Thanks for using our Gitlab plugin, sure we will work on it  :).

**Comment by satrox28** [comment]
Hi @arifrahman4u we have released v0.1.18 to have a People link which redirects to Gitlab Contributors page, please check it.

**Comment by satrox28** [comment]
Please check and let us know, if we can close this issue, thanks @arifrahman4u

**Comment by arifrahman4u** [comment]
Hi Satish,

yes its working Now..
