### ISSUE TITLE
bump backstage dependencies

### ISSUE THREAD

**Issue by Erog38** [loblaw-sre/backstage-plugin-gitlab#95]
Hey all! Looking to implement this into our installation, but unfortunately several packages are out of date. Looks like dependabot has some open PR's but would it be possible to bump backstage scoped versions?

**Comment by satrox28** [comment]
Hi @Erog38 sure, thanks for trying out the plugin and making the contribution. We will test and approve it.

**Comment by Erog38** [comment]
Perfect, thank you for taking a look! :D

**Comment by satrox28** [comment]
Hi @Erog38, thanks for your contribution. The changes are released on v0.1.22.
